# Generated by Django 5.1 on 2025-03-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'codigos',
            },
        ),
        migrations.CreateModel(
            name='Colectores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colector', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'colectores',
            },
        ),
        migrations.CreateModel(
            name='Divisiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.TextField()),
            ],
            options={
                'db_table': 'divisiones',
            },
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.TextField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('familia', models.TextField(blank=True, null=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('nombre_comun', models.TextField(blank=True, null=True)),
                ('sinonimos', models.TextField(blank=True, null=True)),
                ('species_authors', models.TextField(blank=True, null=True)),
                ('genus', models.TextField(blank=True, null=True)),
                ('sp1', models.TextField(blank=True, null=True)),
                ('author1', models.TextField(blank=True, null=True)),
                ('rank1', models.TextField(blank=True, null=True)),
                ('sp2', models.TextField(blank=True, null=True)),
                ('author2', models.TextField(blank=True, null=True)),
                ('rank2', models.TextField(blank=True, null=True)),
                ('sp3', models.TextField(blank=True, null=True)),
                ('author3', models.TextField(blank=True, null=True)),
                ('habito', models.TextField(blank=True, null=True)),
                ('tallos', models.TextField(blank=True, null=True)),
                ('hojas', models.TextField(blank=True, null=True)),
                ('inflorescencia', models.TextField(blank=True, null=True)),
                ('frutos', models.TextField(blank=True, null=True)),
                ('soros', models.TextField(blank=True, null=True)),
                ('distribucion', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especies',
            },
        ),
        migrations.CreateModel(
            name='EspeciesExcluidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=39, null=True)),
                ('species_authors', models.CharField(blank=True, max_length=69, null=True)),
                ('genus', models.CharField(blank=True, max_length=13, null=True)),
                ('sp1', models.CharField(blank=True, max_length=15, null=True)),
                ('autor1', models.CharField(blank=True, max_length=36, null=True)),
                ('rank1', models.CharField(blank=True, max_length=4, null=True)),
                ('sp2', models.CharField(blank=True, max_length=13, null=True)),
                ('autor2', models.CharField(blank=True, max_length=18, null=True)),
                ('comentario', models.CharField(blank=True, max_length=582, null=True)),
            ],
            options={
                'db_table': 'especies_excluidas',
            },
        ),
        migrations.CreateModel(
            name='EspeciesFotosVivas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('familiy', models.CharField(blank=True, max_length=25, null=True)),
                ('photo_name', models.TextField(blank=True, null=True)),
                ('gallery', models.CharField(blank=True, max_length=6, null=True)),
                ('comment', models.CharField(blank=True, max_length=20, null=True)),
                ('species', models.CharField(blank=True, max_length=54, null=True)),
                ('species_authors', models.CharField(blank=True, max_length=128, null=True)),
                ('genus', models.CharField(blank=True, max_length=17, null=True)),
                ('sp1', models.CharField(blank=True, max_length=18, null=True)),
                ('author1', models.CharField(blank=True, max_length=51, null=True)),
                ('rank1', models.CharField(blank=True, max_length=6, null=True)),
                ('sp2', models.CharField(blank=True, max_length=13, null=True)),
                ('author2', models.CharField(blank=True, max_length=40, null=True)),
                ('rank2', models.CharField(blank=True, max_length=4, null=True)),
                ('sp3', models.CharField(blank=True, max_length=8, null=True)),
                ('author3', models.CharField(blank=True, max_length=33, null=True)),
            ],
            options={
                'db_table': 'especies_fotos_vivas',
            },
        ),
        migrations.CreateModel(
            name='EspecimenesFotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo1', models.IntegerField(blank=True, null=True)),
                ('photoname', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=10, null=True)),
                ('accesion', models.IntegerField(blank=True, null=True)),
                ('collector', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=13, null=True)),
                ('addcoll', models.CharField(blank=True, max_length=93, null=True)),
                ('herb', models.CharField(blank=True, max_length=5, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('collected', models.TextField(blank=True, null=True)),
                ('monthname', models.CharField(blank=True, max_length=9, null=True)),
                ('division', models.TextField(blank=True, null=True)),
                ('familiy', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('species_authors', models.TextField(blank=True, null=True)),
                ('detby', models.CharField(blank=True, max_length=47, null=True)),
                ('detdate', models.CharField(blank=True, max_length=16, null=True)),
                ('plantdesc', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('ns', models.CharField(blank=True, max_length=1, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('ew', models.CharField(blank=True, max_length=1, null=True)),
                ('llunit', models.CharField(blank=True, max_length=3, null=True)),
                ('latlong', models.TextField(blank=True, null=True)),
                ('altitude', models.TextField(blank=True, null=True)),
                ('geodata', models.TextField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=123, null=True)),
                ('genus', models.CharField(blank=True, max_length=17, null=True)),
                ('sp1', models.CharField(blank=True, max_length=28, null=True)),
                ('author1', models.CharField(blank=True, max_length=51, null=True)),
                ('rank1', models.CharField(blank=True, max_length=6, null=True)),
                ('sp2', models.CharField(blank=True, max_length=13, null=True)),
                ('author2', models.CharField(blank=True, max_length=40, null=True)),
                ('rank2', models.CharField(blank=True, max_length=4, null=True)),
                ('sp3', models.CharField(blank=True, max_length=8, null=True)),
                ('author3', models.CharField(blank=True, max_length=33, null=True)),
            ],
            options={
                'db_table': 'especimenes_fotos',
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('familia', models.TextField(blank=True, null=True)),
                ('redirigir', models.TextField(blank=True, null=True)),
                ('division', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('clave_int', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'familias',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(blank=True, max_length=17, null=True)),
                ('familiy', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termino', models.CharField(blank=True, max_length=39, null=True)),
                ('definicion', models.CharField(blank=True, max_length=337, null=True)),
                ('c', models.CharField(blank=True, db_column='C', max_length=39, null=True)),
            ],
            options={
                'db_table': 'glosario',
            },
        ),
        migrations.CreateModel(
            name='Literatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citada', models.CharField(blank=True, max_length=357, null=True)),
            ],
            options={
                'db_table': 'literatura',
            },
        ),
    ]
