# Generated by Django 5.1 on 2025-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='datos_formulario',
            field=models.TextField(blank=True, null=True, verbose_name='Datos del Formulario'),
        ),
    ]
