# Generated by Django 5.1 on 2025-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historial_datos_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.CharField(max_length=150, verbose_name='Usuario'),
        ),
    ]
